
kafka_version: "3.7.1"
kafka_scala_version: "2.12"


kafka_nodes:
  kafka1: 192.168.1.112
  kafka2: 192.168.1.116
  kafka3: 192.168.1.124

# zookeeper.connect 
zk_connect: "192.168.1.102:2181,192.168.1.116:2181,192.168.1.124:2181"


zk_servers:
  - "server.1=192.168.1.102:2888:3888"
  - "server.2=192.168.1.116:2888:3888"
  - "server.3=192.168.1.124:2888:3888"
